### ISSUE TITLE
FIT file initialized as cardio?

### ISSUE THREAD

**Issue by rob-miller** [vtrifonov-esfiddle/Meditate#5]
Thank you for this app, I'm using it almost daily.  

I find that when the activity syncs to Connect on my iPhone (iOS), the 'Activity Type' is set to cardio.  I suspect (with no experience programing CIQ apps) that this is the 'Sport Type / Subtype' in the Session record of the FIT file, and might be a default (?) setting when it is initialized.  The type can be edited within Mobile Connect, with yoga and 'breathwork' as relevant options.  It would be preferable to have this match the Yoga / Meditation (breathwork) setting for the activity on the watch without having to edit.

After editing the change is shown in Garmin [Mobile | Web] Connect, but external systems (like FitnessSyncer.com) seem to only get the unmodified file.

Forerunner 645M if that's relevant.

**Comment by vtrifonov-esfiddle** [comment]
Right now you can change the activity to Yoga. Please have a look at the [user guide](https://github.com/vtrifonov-esfiddle/Meditate/blob/master/UserGuide.md#2-configuring-a-session) for that.
Right now the default activity is Cardio because there is no other more appropriate. **Yoga** activites can only be named **Yoga** vai the CIQ API. Additionally **Breathwork** is only produced only by native Garmin apps. There is no sport type and subtype defined for via the [official CIQ docs](https://developer.garmin.com/connect-iq/api-docs/Toybox/ActivityRecording.html).
In order to generate **Breathwork** I need its Activity **sport** and **sub_sport** enum values. Unfortunately my watch cannot create Breatwork activity natively. Could you please record **Breathwork** activity and either report here those values or upload the .FIT file?

**Comment by rob-miller** [comment]
Thanks for the comments. My watch also does not do breathwork, I edit the
FIT file in mobile Connect on my phone to change the meditation output to
that activity - hmmm, probably that does not sync back to the watch. I will
try to investigate and provide more info.

**Comment by akhar** [comment]
[6099691978.zip](https://github.com/vtrifonov-esfiddle/Meditate/files/5807862/6099691978.zip)
There is .fit file of a Breathwork.

**Comment by vtrifonov-esfiddle** [comment]
Thanks the Breathworks FIT! I released a new version that now saves the Meditate activity type as Breathworks. Use the usual place to download the app:
[Vivoactive 3 app store link](https://apps.garmin.com/en-US/apps/bed7ed4d-07ea-4600-b477-b8911670b64a)
[Other round watches](https://apps.garmin.com/en-US/apps/1cc98099-c08b-4fc7-91e6-0f3615a3ab2c)
